[package]
name = "core_test"
version = "0.1.0"
edition = "2021"

[dependencies]
testing_utils = { path = "../utils" }
rectangles = { path = "../../renderers/rectangles"}
pattern_color = { path = "../../patterns/color" }
